### ISSUE TITLE
训练代码开源咨询

### ISSUE THREAD

**Issue by HanJin0326** [Edision-liu/Multi-Drone-Multi-Object-Detection-and-Tracking#2]
您好，感谢贵团队精彩优质的工作！

真诚询问MIA-Net的训练代码何时可以开放，谢谢！

**Comment by haohaoaaa66** [comment]
> 您好，感谢贵团队精彩优质的工作！
> 
> 真诚询问MIA-Net的训练代码何时可以开放，谢谢！

请问您的问题解决了吗？
